import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'

export class DartGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    // Dart access control: public (default), private (prefix with _)
    const typeName = options.accessControl === 'private' ? `_${name}` : name

    if (definition.description) {
      lines.push(`/// ${definition.description}`)
      if (definition.deprecated) {
        lines.push('/// @deprecated')
      }
    }

    if (definition.enum) {
      lines.push(`enum ${typeName} {`)
      for (const value of definition.enum) {
        const enumName = this.toDartEnumName(value, typeName, options)
        lines.push(`  ${enumName},`)
      }
      lines.push('}')
      return lines.join('\n')
    }

    if (definition.oneOf) {
      lines.push(`// ${typeName} can be one of several types`)
      lines.push(`typedef ${typeName} = dynamic;`)
      return lines.join('\n')
    }

    lines.push(`class ${typeName} {`)

    if (definition.properties) {
      for (const [propName, prop] of Object.entries(definition.properties)) {
        const isRequired = definition.required?.includes(propName)
        const type = this.resolveType(prop, !isRequired)

        if (prop.description) {
          lines.push(`  /// ${prop.description}`)
        }

        lines.push(`  final ${type} ${propName};`)
      }

      lines.push('')
      const params = Object.entries(definition.properties)
        .map(([propName, _]) => {
          const isRequired = definition.required?.includes(propName)
          return isRequired ? `required this.${propName}` : `this.${propName}`
        })
        .join(', ')

      lines.push(`  ${typeName}({${params}});`)
      lines.push('')

      lines.push(`  factory ${typeName}.fromJson(Map<String, dynamic> json) {`)
      lines.push(`    return ${typeName}(`)
      for (const [propName, prop] of Object.entries(definition.properties)) {
        const fromJson = this.generateFromJson(propName, prop)
        lines.push(`      ${propName}: ${fromJson},`)
      }
      lines.push(`    );`)
      lines.push(`  }`)
      lines.push('')

      lines.push(`  Map<String, dynamic> toJson() {`)
      lines.push(`    return {`)
      for (const [propName, prop] of Object.entries(definition.properties)) {
        const toJson = this.generateToJson(propName, prop)
        lines.push(`      '${propName}': ${toJson},`)
      }
      lines.push(`    };`)
      lines.push(`  }`)
    }

    lines.push('}')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `${typeName}?` : typeName
    }

    if (prop.oneOf || prop.enum) {
      // dynamic is already nullable in Dart, don't add ?
      return 'dynamic'
    }

    if (Array.isArray(prop.type)) {
      if (prop.type.includes('null')) {
        const nonNullTypes = prop.type.filter((t) => t !== 'null')
        if (nonNullTypes.length === 1) {
          return `${this.mapType(nonNullTypes[0], prop)}?`
        }
      }
      // dynamic is already nullable in Dart, don't add ?
      return 'dynamic'
    }

    const type = prop.type || 'dynamic'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return optional ? `List<${itemType}>?` : `List<${itemType}>`
      }
      return optional ? 'List<dynamic>?' : 'List<dynamic>'
    }

    if (type === 'object') {
      return optional ? 'Map<String, dynamic>?' : 'Map<String, dynamic>'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `${mappedType}?` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'String',
      number: 'double',
      integer: 'int',
      boolean: 'bool',
      null: 'dynamic',
      any: 'dynamic',
    }

    if (prop.format === 'date-time') {
      return 'DateTime'
    }

    return typeMap[type] || 'dynamic'
  }

  private generateFromJson(propName: string, prop: SchemaProperty): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return `json['${propName}'] != null ? ${typeName}.fromJson(json['${propName}']) : null`
    }

    if (prop.type === 'array' && prop.items?.$ref) {
      const itemType = prop.items.$ref.split('/').pop()!
      return `(json['${propName}'] as List?)?.map((e) => ${itemType}.fromJson(e)).toList()`
    }

    if (prop.format === 'date-time') {
      return `json['${propName}'] != null ? DateTime.parse(json['${propName}']) : null`
    }

    return `json['${propName}']`
  }

  private generateToJson(propName: string, prop: SchemaProperty): string {
    if (prop.$ref) {
      return `${propName}?.toJson()`
    }

    if (prop.type === 'array' && prop.items?.$ref) {
      return `${propName}?.map((e) => e.toJson()).toList()`
    }

    if (prop.format === 'date-time') {
      return `${propName}?.toIso8601String()`
    }

    return propName
  }

  private toDartEnumName(value: string, typeName?: string, options?: GeneratorOptions): string {
    // Check for override first
    if (typeName && options?.overrides?.enumNames?.[typeName]?.[value]) {
      return options.overrides.enumNames[typeName][value]
    }

    // Remove any special characters that aren't valid in Dart identifiers
    const sanitized = value.replace(/[^a-zA-Z0-9_-]/g, '')
    return sanitized.replace(/-/g, '_')
  }
}
