import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'

export class GoGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []
    const packageName = options.namespace || 'models'

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')
    lines.push(`package ${packageName}`)
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    // Check if we need to import time
    const needsTimeImport = this.needsTimeImport(schema)
    if (needsTimeImport) {
      lines.push('import (')
      lines.push('    "time"')
      lines.push(')')
      lines.push('')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  private needsTimeImport(schema: JSONSchema): boolean {
    if (!schema.definitions) return false

    for (const definition of Object.values(schema.definitions)) {
      if (this.definitionUsesTime(definition)) {
        return true
      }
    }
    return false
  }

  private definitionUsesTime(definition: SchemaDefinition): boolean {
    if (definition.format === 'date-time') return true

    if (definition.properties) {
      for (const prop of Object.values(definition.properties)) {
        if (this.propertyUsesTime(prop)) return true
      }
    }

    if (definition.items) {
      if (this.propertyUsesTime(definition.items)) return true
    }

    return false
  }

  private propertyUsesTime(prop: SchemaProperty): boolean {
    if (prop.format === 'date-time') return true

    if (prop.properties) {
      for (const nestedProp of Object.values(prop.properties)) {
        if (this.propertyUsesTime(nestedProp)) return true
      }
    }

    if (prop.items) {
      if (this.propertyUsesTime(prop.items)) return true
    }

    return false
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    // In Go, uppercase = exported (public), lowercase = unexported (package-private)
    const typeName = options.accessControl === 'package' ?
                     name.charAt(0).toLowerCase() + name.slice(1) :
                     name

    if (definition.description) {
      lines.push(`// ${typeName} ${definition.description}`)
      if (definition.deprecated) {
        lines.push('// Deprecated')
      }
    }

    if (definition.enum) {
      lines.push(`type ${typeName} string`)
      lines.push('')
      lines.push('const (')
      for (const value of definition.enum) {
        const constName = this.toConstName(value)
        lines.push(`    ${typeName}${constName} ${typeName} = "${value}"`)
      }
      lines.push(')')
      return lines.join('\n')
    }

    if (definition.oneOf) {
      lines.push(`type ${typeName} interface{}`)
      lines.push(`// ${typeName} can be one of the following types:`)
      for (const def of definition.oneOf) {
        lines.push(`// - ${this.resolveType(def, false)}`)
      }
      return lines.join('\n')
    }

    lines.push(`type ${typeName} struct {`)

    if (definition.properties) {
      for (const [propName, prop] of Object.entries(definition.properties)) {
        const isRequired = definition.required?.includes(propName)
        const goName = this.toGoName(propName)
        const type = this.resolveType(prop, !isRequired)
        const jsonTag = `json:"${propName}${isRequired ? '' : ',omitempty'}"`

        if (prop.description) {
          lines.push(`    // ${prop.description}`)
        }

        lines.push(`    ${goName} ${type} \`${jsonTag}\``)
      }
    }

    lines.push('}')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `*${typeName}` : typeName
    }

    if (prop.oneOf) {
      return 'interface{}'
    }

    if (prop.enum) {
      return 'string'
    }

    if (Array.isArray(prop.type)) {
      if (prop.type.includes('null')) {
        const nonNullTypes = prop.type.filter((t) => t !== 'null')
        if (nonNullTypes.length === 1) {
          return `*${this.mapType(nonNullTypes[0], prop)}`
        }
      }
      return 'interface{}'
    }

    const type = prop.type || 'interface{}'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return `[]${itemType}`
      }
      return '[]interface{}'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return 'map[string]interface{}'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        return `map[string]${valueType}`
      }
      return 'map[string]interface{}'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `*${mappedType}` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'string',
      number: 'float64',
      integer: 'int64',
      boolean: 'bool',
      null: 'interface{}',
      any: 'interface{}',
    }

    if (prop.format === 'date-time') {
      return 'time.Time'
    }

    if (prop.format === 'uuid') {
      return 'string'
    }

    return typeMap[type] || 'interface{}'
  }

  private toGoName(name: string): string {
    return name
      .split('_')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  }

  private toConstName(value: string): string {
    return value
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  }
}
