import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'

export class KotlinGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []
    const packageName = options.namespace || 'com.supabase.models'

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')
    lines.push(`package ${packageName}`)
    lines.push('')
    lines.push('import kotlinx.serialization.Serializable')
    lines.push('import kotlinx.serialization.SerialName')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    // Kotlin access control: public (default), private, internal, protected
    const accessControl = options.accessControl === 'public' ? '' : // public is default
                         options.accessControl === 'private' ? 'private ' :
                         options.accessControl === 'internal' ? 'internal ' :
                         options.accessControl === 'protected' ? 'protected ' :
                         '' // Default to public

    if (definition.description) {
      lines.push(`/**`)
      lines.push(` * ${definition.description}`)
      if (definition.deprecated) {
        lines.push(` * @deprecated`)
      }
      lines.push(` */`)
    }

    lines.push('@Serializable')

    if (definition.enum) {
      lines.push(`${accessControl}enum class ${name}(val value: String) {`)
      for (const value of definition.enum) {
        const enumName = this.toKotlinEnumName(value, name, options)
        lines.push(`    @SerialName("${value}")`)
        lines.push(`    ${enumName}("${value}"),`)
      }
      lines.push('}')
      return lines.join('\n')
    }

    if (definition.oneOf) {
      lines.push(`// ${name} can be one of several types`)
      lines.push(`${accessControl}typealias ${name} = Any`)
      return lines.join('\n')
    }

    lines.push(`${accessControl}data class ${name}(`)

    if (definition.properties) {
      const props = Object.entries(definition.properties)
      for (let i = 0; i < props.length; i++) {
        const [propName, prop] = props[i]
        const isRequired = definition.required?.includes(propName)
        const type = this.resolveType(prop, !isRequired)
        const isLast = i === props.length - 1

        if (prop.description) {
          lines.push(`    /** ${prop.description} */`)
        }

        if (propName !== this.toKotlinName(propName)) {
          lines.push(`    @SerialName("${propName}")`)
        }

        const defaultValue = !isRequired ? ' = null' : ''
        lines.push(`    val ${this.toKotlinName(propName)}: ${type}${defaultValue}${isLast ? '' : ','}`)
      }
    }

    lines.push(')')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `${typeName}?` : typeName
    }

    if (prop.oneOf) {
      return optional ? 'Any?' : 'Any'
    }

    if (prop.enum) {
      return optional ? 'String?' : 'String'
    }

    if (Array.isArray(prop.type)) {
      if (prop.type.includes('null')) {
        const nonNullTypes = prop.type.filter((t) => t !== 'null')
        if (nonNullTypes.length === 1) {
          return `${this.mapType(nonNullTypes[0], prop)}?`
        }
      }
      return optional ? 'Any?' : 'Any'
    }

    const type = prop.type || 'Any'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return optional ? `List<${itemType}>?` : `List<${itemType}>`
      }
      return optional ? 'List<Any>?' : 'List<Any>'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return optional ? 'Map<String, Any>?' : 'Map<String, Any>'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        return optional ? `Map<String, ${valueType}>?` : `Map<String, ${valueType}>`
      }
      return optional ? 'Map<String, Any>?' : 'Map<String, Any>'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `${mappedType}?` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'String',
      number: 'Double',
      integer: 'Long',
      boolean: 'Boolean',
      null: 'Any',
      any: 'Any',
    }

    if (prop.format === 'date-time') {
      return 'String'
    }

    return typeMap[type] || 'Any'
  }

  private toKotlinName(name: string): string {
    if (name.includes('_')) {
      const parts = name.split('_')
      return parts[0] + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
    }
    return name
  }

  private toKotlinEnumName(value: string, typeName?: string, options?: GeneratorOptions): string {
    // Check for override first
    if (typeName && options?.overrides?.enumNames?.[typeName]?.[value]) {
      return options.overrides.enumNames[typeName][value].toUpperCase()
    }

    // Remove any special characters that aren't valid in Kotlin identifiers
    const sanitized = value.replace(/[^a-zA-Z0-9_-]/g, '')
    return sanitized.toUpperCase().replace(/-/g, '_')
  }
}
