import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'

export class PythonGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('# Generated by @supabase/sdkdev')
    lines.push('# Do not edit this file directly')
    lines.push('')
    lines.push('from typing import Optional, List, Dict, Union, Any, TypedDict')
    lines.push('from datetime import datetime')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    if (definition.enum) {
      lines.push(`class ${name}:`)
      if (definition.description) {
        lines.push(`    """${definition.description}"""`)
      }
      for (const value of definition.enum) {
        const constName = value.toUpperCase().replace(/-/g, '_')
        lines.push(`    ${constName} = "${value}"`)
      }
      return lines.join('\n')
    }

    if (definition.oneOf) {
      const types = definition.oneOf.map((def) => this.resolveType(def, false)).join(', ')
      lines.push(`${name} = Union[${types}]`)
      if (definition.description) {
        lines.push(`"""${definition.description}"""`)
      }
      return lines.join('\n')
    }

    lines.push(`class ${name}(TypedDict${definition.required ? '' : ', total=False'}):`)

    if (definition.description) {
      lines.push(`    """${definition.description}`)
      if (definition.deprecated) {
        lines.push(`    @deprecated`)
      }
      lines.push(`    """`)
    }

    if (definition.properties) {
      const hasContent = Object.keys(definition.properties).length > 0
      if (!hasContent && !definition.description) {
        lines.push('    pass')
      }

      for (const [propName, prop] of Object.entries(definition.properties)) {
        const isRequired = definition.required?.includes(propName)
        const type = this.resolveType(prop, !isRequired)

        if (prop.description) {
          lines.push(`    # ${prop.description}`)
        }

        lines.push(`    ${propName}: ${type}`)
      }
    } else {
      if (!definition.description) {
        lines.push('    pass')
      }
    }

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `Optional[${typeName}]` : typeName
    }

    if (prop.oneOf) {
      const types = prop.oneOf.map((def) => this.resolveType(def, false)).join(', ')
      const unionType = `Union[${types}]`
      return optional ? `Optional[${unionType}]` : unionType
    }

    if (prop.enum) {
      const values = prop.enum.map((v) => `"${v}"`).join(', ')
      const literalType = `Literal[${values}]`
      return optional ? `Optional[${literalType}]` : literalType
    }

    if (Array.isArray(prop.type)) {
      const types = prop.type.map((t) => this.mapType(t, prop)).join(', ')
      const unionType = types.includes(',') ? `Union[${types}]` : types
      return optional ? `Optional[${unionType}]` : unionType
    }

    const type = prop.type || 'Any'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        const listType = `List[${itemType}]`
        return optional ? `Optional[${listType}]` : listType
      }
      return optional ? 'Optional[List[Any]]' : 'List[Any]'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return optional ? 'Optional[Dict[str, Any]]' : 'Dict[str, Any]'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        const dictType = `Dict[str, ${valueType}]`
        return optional ? `Optional[${dictType}]` : dictType
      }
      return optional ? 'Optional[Dict[str, Any]]' : 'Dict[str, Any]'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `Optional[${mappedType}]` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'str',
      number: 'float',
      integer: 'int',
      boolean: 'bool',
      null: 'None',
      any: 'Any',
    }

    if (prop.format === 'date-time') {
      return 'datetime'
    }

    return typeMap[type] || 'Any'
  }
}
