import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'
import {
  isTypeExcluded,
  isPropertyExcluded,
  filterEnumValues,
  getEnumValueName,
} from '../utils/overrides.js'

export class PythonGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('# Generated by @supabase/sdkdev')
    lines.push('# Do not edit this file directly')
    lines.push('')
    lines.push('from typing import Optional, List, Dict, Union, Any, Literal')
    lines.push('from datetime import datetime')
    lines.push('from pydantic import BaseModel, Field')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      // Skip excluded types
      if (isTypeExcluded(name, options.overrides)) {
        continue
      }

      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    if (definition.enum) {
      lines.push(`class ${name}:`)
      if (definition.description) {
        lines.push(`    """${definition.description}"""`)
      }

      // Filter out excluded enum values
      const enumValues = filterEnumValues(name, definition.enum, options.overrides)

      for (const value of enumValues) {
        const constName = this.toPythonConstName(value, name, options)
        lines.push(`    ${constName} = "${value}"`)
      }
      return lines.join('\n')
    }

    if (definition.oneOf) {
      const types = definition.oneOf.map((def) => this.resolveType(def, false)).join(', ')
      lines.push(`${name} = Union[${types}]`)
      if (definition.description) {
        lines.push(`"""${definition.description}"""`)
      }
      return lines.join('\n')
    }

    lines.push(`class ${name}(BaseModel):`)

    if (definition.description) {
      lines.push(`    """${definition.description}`)
      if (definition.deprecated) {
        lines.push(`    @deprecated`)
      }
      lines.push(`    """`)
    }

    if (definition.properties) {
      const hasContent = Object.keys(definition.properties).length > 0
      if (!hasContent && !definition.description) {
        lines.push('    pass')
      }

      for (const [propName, prop] of Object.entries(definition.properties)) {
        // Skip excluded properties
        if (isPropertyExcluded(name, propName, options.overrides)) {
          continue
        }

        const isRequired = definition.required?.includes(propName)
        const baseType = this.resolveType(prop, false)

        // Check if the type already includes None (e.g., Union[str, None])
        const typeIncludesNone = baseType.includes('Union[') && baseType.includes('None')

        // For Pydantic, we use Optional[T] with default=None for optional fields
        // But if the type already includes None in a Union, don't double-wrap
        let type: string
        let defaultValue: string

        if (isRequired) {
          type = baseType
          defaultValue = ''
        } else if (typeIncludesNone) {
          // Already nullable, just use as-is
          type = baseType
          defaultValue = ' = None'
        } else {
          // Wrap with Optional
          type = `Optional[${baseType}]`
          defaultValue = ' = None'
        }

        if (prop.description) {
          // Use Field with description for better Pydantic integration
          const escapedDesc = prop.description.replace(/"/g, '\\"')
          lines.push(`    ${propName}: ${type} = Field(${defaultValue ? 'default=None, ' : ''}description="${escapedDesc}")`)
        } else {
          lines.push(`    ${propName}: ${type}${defaultValue}`)
        }
      }
    } else {
      if (!definition.description) {
        lines.push('    pass')
      }
    }

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    // Note: optional parameter is kept for API compatibility but not used
    // Optionality is now handled at the field level with Optional[T] = None
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return typeName
    }

    if (prop.oneOf) {
      const types = prop.oneOf.map((def) => this.resolveType(def, false)).join(', ')
      return `Union[${types}]`
    }

    if (prop.enum) {
      const values = prop.enum.map((v) => `"${v}"`).join(', ')
      return `Literal[${values}]`
    }

    if (Array.isArray(prop.type)) {
      const types = prop.type.map((t) => this.mapType(t, prop)).join(', ')
      return types.includes(',') ? `Union[${types}]` : types
    }

    const type = prop.type || 'Any'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return `List[${itemType}]`
      }
      return 'List[Any]'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return 'Dict[str, Any]'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        return `Dict[str, ${valueType}]`
      }
      return 'Dict[str, Any]'
    }

    return this.mapType(type, prop)
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'str',
      number: 'float',
      integer: 'int',
      boolean: 'bool',
      null: 'None',
      any: 'Any',
    }

    if (prop.format === 'date-time') {
      return 'datetime'
    }

    return typeMap[type] || 'Any'
  }

  private toPythonConstName(value: string, typeName?: string, options?: GeneratorOptions): string {
    // Check for override first
    const overrideName = typeName ? getEnumValueName(typeName, value, options?.overrides) : undefined
    if (overrideName) {
      return overrideName.toUpperCase()
    }

    // Remove any special characters that aren't valid in Python identifiers
    const sanitized = value.replace(/[^a-zA-Z0-9_-]/g, '')
    return sanitized.toUpperCase().replace(/-/g, '_')
  }
}
