import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'
import {
  isTypeExcluded,
  isPropertyExcluded,
  filterEnumValues,
  getEnumValueName,
} from '../utils/overrides.js'

export class RustGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')
    lines.push('use serde::{Deserialize, Serialize};')
    lines.push('use chrono::{DateTime, Utc};')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      // Skip excluded types
      if (isTypeExcluded(name, options.overrides)) {
        continue
      }

      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    // Rust access control: pub (public), nothing (private to module)
    const accessControl = options.accessControl === 'private' ? '' :
                         'pub ' // Default to pub for library code

    if (definition.description) {
      lines.push(`/// ${definition.description}`)
      if (definition.deprecated) {
        lines.push('/// #[deprecated]')
      }
    }

    lines.push('#[derive(Debug, Clone, Serialize, Deserialize)]')

    if (definition.enum) {
      lines.push('#[serde(rename_all = "kebab-case")]')
      lines.push(`${accessControl}enum ${name} {`)

      // Filter out excluded enum values
      const enumValues = filterEnumValues(name, definition.enum, options.overrides)

      for (const value of enumValues) {
        const variantName = this.toRustName(value, name, options)
        if (variantName !== value) {
          lines.push(`    #[serde(rename = "${value}")]`)
        }
        lines.push(`    ${variantName},`)
      }
      lines.push('}')
      return lines.join('\n')
    }

    if (definition.oneOf) {
      lines.push('#[serde(untagged)]')
      lines.push(`${accessControl}enum ${name} {`)
      definition.oneOf.forEach((_, idx) => {
        lines.push(`    Variant${idx + 1}(serde_json::Value),`)
      })
      lines.push('}')
      return lines.join('\n')
    }

    lines.push(`${accessControl}struct ${name} {`)

    if (definition.properties) {
      for (const [propName, prop] of Object.entries(definition.properties)) {
        // Skip excluded properties
        if (isPropertyExcluded(name, propName, options.overrides)) {
          continue
        }

        const isRequired = definition.required?.includes(propName)
        const type = this.resolveType(prop, !isRequired)

        if (prop.description) {
          lines.push(`    /// ${prop.description}`)
        }

        const rustName = this.toSnakeCase(propName)
        const escapedRustName = this.escapeRustKeyword(rustName)

        // Add serde rename if the Rust field name differs from the JSON property name
        if (escapedRustName !== propName) {
          lines.push(`    #[serde(rename = "${propName}")]`)
        }

        if (!isRequired) {
          lines.push(`    #[serde(skip_serializing_if = "Option::is_none")]`)
        }

        lines.push(`    ${accessControl}${escapedRustName}: ${type},`)
      }
    }

    lines.push('}')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `Option<${typeName}>` : typeName
    }

    if (prop.oneOf) {
      return optional ? 'Option<serde_json::Value>' : 'serde_json::Value'
    }

    if (prop.enum) {
      return optional ? 'Option<String>' : 'String'
    }

    if (Array.isArray(prop.type)) {
      if (prop.type.includes('null')) {
        const nonNullTypes = prop.type.filter((t) => t !== 'null')
        if (nonNullTypes.length === 1) {
          return `Option<${this.mapType(nonNullTypes[0], prop)}>`
        }
      }
      return optional ? 'Option<serde_json::Value>' : 'serde_json::Value'
    }

    const type = prop.type || 'serde_json::Value'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return optional ? `Option<Vec<${itemType}>>` : `Vec<${itemType}>`
      }
      return optional ? 'Option<Vec<serde_json::Value>>' : 'Vec<serde_json::Value>'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return optional
            ? 'Option<std::collections::HashMap<String, serde_json::Value>>'
            : 'std::collections::HashMap<String, serde_json::Value>'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        return optional
          ? `Option<std::collections::HashMap<String, ${valueType}>>`
          : `std::collections::HashMap<String, ${valueType}>`
      }
      return optional
        ? 'Option<std::collections::HashMap<String, serde_json::Value>>'
        : 'std::collections::HashMap<String, serde_json::Value>'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `Option<${mappedType}>` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'String',
      number: 'f64',
      integer: 'i64',
      boolean: 'bool',
      null: 'serde_json::Value',
      any: 'serde_json::Value',
    }

    if (prop.format === 'date-time') {
      return 'DateTime<Utc>'
    }

    if (prop.format === 'uuid') {
      return 'String'
    }

    return typeMap[type] || 'serde_json::Value'
  }

  private toRustName(name: string, typeName?: string, options?: GeneratorOptions): string {
    // Check for override first
    const overrideName = typeName ? getEnumValueName(typeName, name, options?.overrides) : undefined
    if (overrideName) {
      return overrideName.charAt(0).toUpperCase() + overrideName.slice(1)
    }

    // Remove any special characters that aren't valid in Rust identifiers
    const sanitized = name.replace(/[^a-zA-Z0-9_-]/g, '')

    return sanitized
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  }

  private toSnakeCase(name: string): string {
    return name.replace(/-/g, '_')
  }

  private escapeRustKeyword(name: string): string {
    // Special case: 'self' cannot be escaped with r# in Rust
    // We need to rename it to something else
    if (name === 'self') {
      return 'self_'
    }

    // List of Rust keywords that need escaping
    const keywords = new Set([
      'as', 'break', 'const', 'continue', 'crate', 'else', 'enum', 'extern',
      'false', 'fn', 'for', 'if', 'impl', 'in', 'let', 'loop', 'match',
      'mod', 'move', 'mut', 'pub', 'ref', 'return', 'Self', 'static',
      'struct', 'super', 'trait', 'true', 'type', 'unsafe', 'use', 'where',
      'while', 'async', 'await', 'dyn', 'abstract', 'become', 'box', 'do',
      'final', 'macro', 'override', 'priv', 'typeof', 'unsized', 'virtual', 'yield'
    ])

    return keywords.has(name) ? `r#${name}` : name
  }
}
