import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'

export class SwiftGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')
    lines.push('import Foundation')
    lines.push('')

    // Add JSON enum for flexible types
    const accessControl = options.accessControl === 'public' ? 'public ' :
                         options.accessControl === 'private' ? 'private ' :
                         options.accessControl === 'internal' ? 'internal ' :
                         'public ' // Default to public for library code

    lines.push(`/// Represents any JSON value`)
    lines.push(`${accessControl}indirect enum JSON: Codable, Hashable {`)
    lines.push(`    case null`)
    lines.push(`    case bool(Bool)`)
    lines.push(`    case number(Double)`)
    lines.push(`    case string(String)`)
    lines.push(`    case array([JSON])`)
    lines.push(`    case object([String: JSON])`)
    lines.push(``)
    lines.push(`    ${accessControl}init(from decoder: Decoder) throws {`)
    lines.push(`        let container = try decoder.singleValueContainer()`)
    lines.push(`        if container.decodeNil() {`)
    lines.push(`            self = .null`)
    lines.push(`        } else if let bool = try? container.decode(Bool.self) {`)
    lines.push(`            self = .bool(bool)`)
    lines.push(`        } else if let number = try? container.decode(Double.self) {`)
    lines.push(`            self = .number(number)`)
    lines.push(`        } else if let string = try? container.decode(String.self) {`)
    lines.push(`            self = .string(string)`)
    lines.push(`        } else if let array = try? container.decode([JSON].self) {`)
    lines.push(`            self = .array(array)`)
    lines.push(`        } else if let object = try? container.decode([String: JSON].self) {`)
    lines.push(`            self = .object(object)`)
    lines.push(`        } else {`)
    lines.push(`            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Invalid JSON value")`)
    lines.push(`        }`)
    lines.push(`    }`)
    lines.push(``)
    lines.push(`    ${accessControl}func encode(to encoder: Encoder) throws {`)
    lines.push(`        var container = encoder.singleValueContainer()`)
    lines.push(`        switch self {`)
    lines.push(`        case .null:`)
    lines.push(`            try container.encodeNil()`)
    lines.push(`        case .bool(let bool):`)
    lines.push(`            try container.encode(bool)`)
    lines.push(`        case .number(let number):`)
    lines.push(`            try container.encode(number)`)
    lines.push(`        case .string(let string):`)
    lines.push(`            try container.encode(string)`)
    lines.push(`        case .array(let array):`)
    lines.push(`            try container.encode(array)`)
    lines.push(`        case .object(let object):`)
    lines.push(`            try container.encode(object)`)
    lines.push(`        }`)
    lines.push(`    }`)
    lines.push(`}`)
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    // Swift access control: public, internal (default), private, fileprivate
    const accessControl = options.accessControl === 'public' ? 'public ' :
                         options.accessControl === 'private' ? 'private ' :
                         options.accessControl === 'internal' ? 'internal ' :
                         'public ' // Default to public for library code

    if (definition.description) {
      lines.push(`/// ${definition.description}`)
      if (definition.deprecated) {
        lines.push('/// @available(*, deprecated)')
      }
    }

    if (definition.enum) {
      lines.push(`${accessControl}struct ${name}: RawRepresentable, Codable, Hashable, Equatable, ExpressibleByStringLiteral {`)
      lines.push(`    ${accessControl}let rawValue: String`)
      lines.push(``)

      for (const value of definition.enum) {
        const staticName = this.toSwiftStaticName(value)
        lines.push(`    ${accessControl}static let ${staticName} = ${name}(rawValue: "${value}")`)
      }

      lines.push(``)
      lines.push(`    ${accessControl}init(rawValue: String) {`)
      lines.push(`        self.rawValue = rawValue`)
      lines.push(`    }`)
      lines.push(``)
      lines.push(`    ${accessControl}init(stringLiteral value: String) {`)
      lines.push(`        self.rawValue = value`)
      lines.push(`    }`)
      lines.push('}')
      return lines.join('\n')
    }

    if (definition.oneOf) {
      lines.push(`${accessControl}enum ${name}: Codable, Hashable {`)
      definition.oneOf.forEach((_, idx) => {
        lines.push(`    case variant${idx + 1}`)
      })
      lines.push('}')
      return lines.join('\n')
    }

    lines.push(`${accessControl}struct ${name}: Codable, Hashable {`)

    if (definition.properties) {
      const codingKeyMappings: Array<{ swift: string; json: string }> = []
      let needsCodingKeys = false

      for (const [propName, prop] of Object.entries(definition.properties)) {
        const isRequired = definition.required?.includes(propName)
        const type = this.resolveType(prop, !isRequired)

        if (prop.description) {
          lines.push(`    /// ${prop.description}`)
        }

        const swiftName = this.toSwiftName(propName)
        lines.push(`    ${accessControl}let ${swiftName}: ${type}`)

        // Always add to mappings list
        codingKeyMappings.push({ swift: swiftName, json: propName })

        // Track if we need CodingKeys (when names differ)
        if (swiftName !== propName) {
          needsCodingKeys = true
        }
      }

      // Generate CodingKeys enum if any property needs name mapping
      // When present, CodingKeys must include ALL properties
      if (needsCodingKeys) {
        lines.push(``)
        lines.push(`    enum CodingKeys: String, CodingKey {`)
        for (const mapping of codingKeyMappings) {
          if (mapping.swift !== mapping.json) {
            lines.push(`        case ${mapping.swift} = "${mapping.json}"`)
          } else {
            lines.push(`        case ${mapping.swift}`)
          }
        }
        lines.push(`    }`)
      }
    }

    lines.push('}')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `${typeName}?` : typeName
    }

    if (prop.oneOf) {
      return optional ? 'JSON?' : 'JSON'
    }

    if (prop.enum) {
      return optional ? 'String?' : 'String'
    }

    if (Array.isArray(prop.type)) {
      if (prop.type.includes('null')) {
        const nonNullTypes = prop.type.filter((t) => t !== 'null')
        if (nonNullTypes.length === 1) {
          return `${this.mapType(nonNullTypes[0], prop)}?`
        }
      }
      return optional ? 'JSON?' : 'JSON'
    }

    const type = prop.type || 'JSON'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return optional ? `[${itemType}]?` : `[${itemType}]`
      }
      return optional ? '[JSON]?' : '[JSON]'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return optional ? '[String: JSON]?' : '[String: JSON]'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        return optional ? `[String: ${valueType}]?` : `[String: ${valueType}]`
      }
      return optional ? '[String: JSON]?' : '[String: JSON]'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `${mappedType}?` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'String',
      number: 'Double',
      integer: 'Int',
      boolean: 'Bool',
      null: 'JSON',
      any: 'JSON',
    }

    if (prop.format === 'date-time') {
      return 'Date'
    }

    if (prop.format === 'uuid') {
      return 'UUID'
    }

    return typeMap[type] || 'JSON'
  }

  private toSwiftName(name: string): string {
    if (name.includes('_')) {
      const parts = name.split('_')
      return parts[0] + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
    }
    return name
  }

  private toSwiftStaticName(value: string): string {
    // Convert kebab-case or snake_case to camelCase for Swift static property names
    // e.g., "ap-northeast-1" -> "apNortheast1"
    // e.g., "us_west_2" -> "usWest2"
    const normalized = value.replace(/[-_]/g, ' ')
    const parts = normalized.split(' ')

    if (parts.length === 0) return value

    // First part stays lowercase, rest are capitalized
    return parts[0].toLowerCase() +
           parts.slice(1).map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
  }
}
