import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'

export class SwiftGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')
    lines.push('import Foundation')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []

    // Swift access control: public, internal (default), private, fileprivate
    const accessControl = options.accessControl === 'public' ? 'public ' :
                         options.accessControl === 'private' ? 'private ' :
                         options.accessControl === 'internal' ? 'internal ' :
                         'public ' // Default to public for library code

    if (definition.description) {
      lines.push(`/// ${definition.description}`)
      if (definition.deprecated) {
        lines.push('/// @available(*, deprecated)')
      }
    }

    if (definition.enum) {
      lines.push(`${accessControl}struct ${name}: RawRepresentable, Codable, Equatable, Hashable, ExpressibleByStringLiteral {`)
      lines.push(`    ${accessControl}let rawValue: String`)
      lines.push(``)

      for (const value of definition.enum) {
        const staticName = this.toSwiftStaticName(value)
        lines.push(`    ${accessControl}static let ${staticName} = ${name}(rawValue: "${value}")`)
      }

      lines.push(``)
      lines.push(`    ${accessControl}init(rawValue: String) {`)
      lines.push(`        self.rawValue = rawValue`)
      lines.push(`    }`)
      lines.push(``)
      lines.push(`    ${accessControl}init(stringLiteral value: String) {`)
      lines.push(`        self.rawValue = value`)
      lines.push(`    }`)
      lines.push('}')
      return lines.join('\n')
    }

    if (definition.oneOf) {
      lines.push(`${accessControl}enum ${name}: Codable {`)
      definition.oneOf.forEach((_, idx) => {
        lines.push(`    case variant${idx + 1}`)
      })
      lines.push('}')
      return lines.join('\n')
    }

    lines.push(`${accessControl}struct ${name}: Codable {`)

    if (definition.properties) {
      const codingKeyMappings: Array<{ swift: string; json: string }> = []

      for (const [propName, prop] of Object.entries(definition.properties)) {
        const isRequired = definition.required?.includes(propName)
        const type = this.resolveType(prop, !isRequired)

        if (prop.description) {
          lines.push(`    /// ${prop.description}`)
        }

        const swiftName = this.toSwiftName(propName)
        lines.push(`    ${accessControl}let ${swiftName}: ${type}`)

        if (swiftName !== propName) {
          codingKeyMappings.push({ swift: swiftName, json: propName })
        }
      }

      // Generate CodingKeys enum once if there are any mappings
      if (codingKeyMappings.length > 0) {
        lines.push(``)
        lines.push(`    enum CodingKeys: String, CodingKey {`)
        for (const mapping of codingKeyMappings) {
          lines.push(`        case ${mapping.swift} = "${mapping.json}"`)
        }
        lines.push(`    }`)
      }
    }

    lines.push('}')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition, optional: boolean): string {
    if (prop.$ref) {
      const typeName = prop.$ref.split('/').pop()!
      return optional ? `${typeName}?` : typeName
    }

    if (prop.oneOf) {
      return 'AnyCodable'
    }

    if (prop.enum) {
      return optional ? 'String?' : 'String'
    }

    if (Array.isArray(prop.type)) {
      if (prop.type.includes('null')) {
        const nonNullTypes = prop.type.filter((t) => t !== 'null')
        if (nonNullTypes.length === 1) {
          return `${this.mapType(nonNullTypes[0], prop)}?`
        }
      }
      return optional ? 'AnyCodable?' : 'AnyCodable'
    }

    const type = prop.type || 'AnyCodable'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items, false)
        return optional ? `[${itemType}]?` : `[${itemType}]`
      }
      return optional ? '[AnyCodable]?' : '[AnyCodable]'
    }

    if (type === 'object') {
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return optional ? '[String: AnyCodable]?' : '[String: AnyCodable]'
        }
        const valueType = this.resolveType(prop.additionalProperties, false)
        return optional ? `[String: ${valueType}]?` : `[String: ${valueType}]`
      }
      return optional ? '[String: AnyCodable]?' : '[String: AnyCodable]'
    }

    const mappedType = this.mapType(type, prop)
    return optional ? `${mappedType}?` : mappedType
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'String',
      number: 'Double',
      integer: 'Int',
      boolean: 'Bool',
      null: 'AnyCodable',
      any: 'AnyCodable',
    }

    if (prop.format === 'date-time') {
      return 'Date'
    }

    if (prop.format === 'uuid') {
      return 'UUID'
    }

    return typeMap[type] || 'AnyCodable'
  }

  private toSwiftName(name: string): string {
    if (name.includes('_')) {
      const parts = name.split('_')
      return parts[0] + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
    }
    return name
  }

  private toSwiftStaticName(value: string): string {
    // Convert kebab-case or snake_case to camelCase for Swift static property names
    // e.g., "ap-northeast-1" -> "apNortheast1"
    // e.g., "us_west_2" -> "usWest2"
    const normalized = value.replace(/[-_]/g, ' ')
    const parts = normalized.split(' ')

    if (parts.length === 0) return value

    // First part stays lowercase, rest are capitalized
    return parts[0].toLowerCase() +
           parts.slice(1).map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
  }
}
