import {
  JSONSchema,
  SchemaDefinition,
  SchemaProperty,
  CodeGenerator,
  GeneratorOptions,
} from '../types.js'
import {
  isTypeExcluded,
  isPropertyExcluded,
  filterEnumValues,
  getEnumValueName,
} from '../utils/overrides.js'

export class TypeScriptGenerator implements CodeGenerator {
  generate(schema: JSONSchema, options: GeneratorOptions = {}): string {
    const lines: string[] = []

    lines.push('// Generated by @supabase/sdkdev')
    lines.push('// Do not edit this file directly')
    lines.push('')

    if (!schema.definitions) {
      throw new Error('Schema must have definitions')
    }

    for (const [name, definition] of Object.entries(schema.definitions)) {
      // Skip excluded types
      if (isTypeExcluded(name, options.overrides)) {
        continue
      }

      lines.push(this.generateType(name, definition, options))
      lines.push('')
    }

    return lines.join('\n')
  }

  generateType(
    name: string,
    definition: SchemaDefinition,
    options: GeneratorOptions = {}
  ): string {
    const lines: string[] = []
    const accessControl = options.accessControl === 'public' ? 'export ' :
                         options.accessControl === 'private' ? '' :
                         'export ' // Default to export

    if (definition.description) {
      lines.push(`/**`)
      lines.push(` * ${definition.description}`)
      if (definition.deprecated) {
        lines.push(` * @deprecated`)
      }
      lines.push(` */`)
    }

    if (definition.enum) {
      // Filter out excluded enum values
      const enumValues = filterEnumValues(name, definition.enum, options.overrides)
      lines.push(`${accessControl}type ${name} = ${enumValues.map((v) => `'${v}'`).join(' | ')}`)
      return lines.join('\n')
    }

    if (definition.oneOf) {
      const types = definition.oneOf.map((def) => this.resolveType(def)).join(' | ')
      lines.push(`${accessControl}type ${name} = ${types}`)
      return lines.join('\n')
    }

    lines.push(`${accessControl}interface ${name} {`)

    if (definition.properties) {
      for (const [propName, prop] of Object.entries(definition.properties)) {
        // Skip excluded properties
        if (isPropertyExcluded(name, propName, options.overrides)) {
          continue
        }

        const isRequired = definition.required?.includes(propName)
        const optional = isRequired ? '' : '?'

        if (prop.description) {
          lines.push(`  /**`)
          lines.push(`   * ${prop.description}`)
          if (prop.deprecated) {
            lines.push(`   * @deprecated`)
          }
          lines.push(`   */`)
        }

        const type = this.resolveType(prop)
        lines.push(`  ${propName}${optional}: ${type}`)
      }
    }

    if (definition.additionalProperties) {
      if (typeof definition.additionalProperties === 'boolean') {
        lines.push(`  [key: string]: any`)
      } else {
        const type = this.resolveType(definition.additionalProperties)
        lines.push(`  [key: string]: ${type}`)
      }
    }

    lines.push('}')

    return lines.join('\n')
  }

  private resolveType(prop: SchemaProperty | SchemaDefinition): string {
    if (prop.$ref) {
      return prop.$ref.split('/').pop()!
    }

    if (prop.oneOf) {
      return prop.oneOf.map((def) => this.resolveType(def)).join(' | ')
    }

    if (prop.enum) {
      return prop.enum.map((v) => `'${v}'`).join(' | ')
    }

    if (Array.isArray(prop.type)) {
      return prop.type.map((t) => this.mapType(t, prop)).join(' | ')
    }

    const type = prop.type || 'any'

    if (type === 'array') {
      if (prop.items) {
        const itemType = this.resolveType(prop.items)
        return `${itemType}[]`
      }
      return 'any[]'
    }

    if (type === 'object') {
      if (prop.properties) {
        const props = Object.entries(prop.properties)
          .map(([key, value]) => {
            const isRequired = prop.required?.includes(key)
            const optional = isRequired ? '' : '?'
            return `${key}${optional}: ${this.resolveType(value)}`
          })
          .join(', ')
        return `{ ${props} }`
      }
      if (prop.additionalProperties) {
        if (typeof prop.additionalProperties === 'boolean') {
          return 'Record<string, any>'
        }
        const valueType = this.resolveType(prop.additionalProperties)
        return `Record<string, ${valueType}>`
      }
      return 'Record<string, any>'
    }

    return this.mapType(type, prop)
  }

  private mapType(type: string, prop: SchemaProperty | SchemaDefinition): string {
    const typeMap: Record<string, string> = {
      string: 'string',
      number: 'number',
      integer: 'number',
      boolean: 'boolean',
      null: 'null',
      any: 'any',
    }

    if (prop.format === 'date-time') {
      return 'string'
    }

    return typeMap[type] || 'any'
  }
}
